# Generated by Django 4.1.1 on 2022-09-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogsdetails_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsdetails',
            old_name='email',
            new_name='blog_author',
        ),
    ]
