# Generated by Django 4.1.1 on 2022-09-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_customuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_bloger',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_role',
            field=models.CharField(choices=[('user', 'User'), ('bloger', 'Bloger')], default='---select---', max_length=10),
        ),
    ]
