# Generated by Django 4.1.1 on 2022-09-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_customuser_is_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_role',
            field=models.CharField(choices=[('Reader', 'Reader'), ('bloger', 'Bloger')], default='', max_length=10),
        ),
    ]
