# Generated by Django 4.1.1 on 2022-09-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_customuser_is_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_role',
            field=models.CharField(choices=[('Reader', 'Reader'), ('bloger', 'Bloger')], max_length=10, verbose_name='who are you?'),
        ),
    ]
