# Generated by Django 4.1.1 on 2022-09-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_customuser_is_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_bloger',
            field=models.BooleanField(default=False, verbose_name='bloger'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_user',
            field=models.BooleanField(default=False, verbose_name='user'),
        ),
    ]
