# Generated by Django 4.1.1 on 2022-09-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_customuser_is_bloger_customuser_is_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_user',
            new_name='is_reader',
        ),
    ]
