# Generated by Django 4.1.1 on 2022-09-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_rename_blog_author_blogsdetails_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_bloger',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_blogger',
            field=models.BooleanField(default=False, verbose_name='blogger'),
        ),
    ]
