# Generated by Django 4.1.1 on 2022-09-20 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_remove_customuser_is_bloger_customuser_is_blogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.blogsdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='email address'),
        ),
    ]
