# Generated by Django 4.1.1 on 2022-09-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_alter_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog_title',
        ),
    ]
