# Generated by Django 4.1.1 on 2022-09-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_remove_comment_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogsdetails',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
