# Generated by Django 4.1.1 on 2022-09-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_comment_blog_id_alter_blogsdetails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogsdetails'),
        ),
    ]
