# Generated by Django 4.0.4 on 2022-09-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_alter_blogsdetails_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_id',
            new_name='blog_title',
        ),
    ]
